include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    always_declare_return_types: true
    eol_at_end_of_file: true