# include: package:very_good_analysis/analysis_options.3.1.0.yaml
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    public_member_api_docs: false
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    always_declare_return_types: true
    eol_at_end_of_file: true
