name: mbl
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  mockito: ^5.3.2
  just_audio: ^0.9.31
  just_audio_background: ^0.0.1-beta.9
  audio_video_progress_bar: ^1.0.0
  rxdart: ^0.27.7
  palette_generator: ^0.3.3+2
  stream_transform: ^2.1.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/environment/development/.env
