#!/usr/bin/env bash

GIT_DIR=$(git rev-parse --git-dir)

echo "Installing hooks..."
# this command creates symlink to our pre-commit script
ln -s ../../githooks/pre-commit $GIT_DIR/hooks/pre-commit
ln -s ../../githooks/pre-push $GIT_DIR/hooks/pre-push
echo "Done!"
